// Generated by CoffeeScript 1.10.0
(function() {
  var canvas;

  canvas = null;

  window.onload = function(e) {
    var cl, ctx;
    canvas = document.getElementById('my_canvas');
    cl = new BaseObject;
    alert('here');
    ctx = canvas.getContext("2d");
    ctx.fillStyle = "#FF0000";
    return ctx.fillRect(20, 20, 150, 100);
  };

}).call(this);

//# sourceMappingURL=app.js.map
