// Generated by CoffeeScript 1.10.0
(function() {
  var canvas;

  canvas = null;

  window.scene = null;

  jQuery(document).ready(function() {
    var timer;
    canvas = document.getElementById('my_canvas');
    window.scene = new Scene(canvas);
    return timer = setInterval(((function(_this) {
      return function() {
        return window.scene.draw_scene();
      };
    })(this)), 100);
  });

}).call(this);

//# sourceMappingURL=app.js.map
