// Generated by CoffeeScript 1.10.0
(function() {
  var canvas;

  canvas = null;

  window.scene = null;

  jQuery(document).ready(function() {
    canvas = document.getElementById('my_canvas');
    return window.scene = new Scene(canvas);
  });

}).call(this);

//# sourceMappingURL=app.js.map
