// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.CameraSettings = (function(superClass) {
    extend(CameraSettings, superClass);

    function CameraSettings(object) {
      this.object = object;
      CameraSettings.__super__.constructor.call(this, this.object);
      this.panel = $('#settings_camera');
      this.camera_position = new ThreeBoxSettings(this.object, this.panel, 'camera_position', 0, -3, 5);
      this.camera_rotate = new ThreeBoxSettings(this.object, this.panel, 'camera_rotate', 0.3, 0, 0);
      this.settings = [this.camera_rotate, this.camera_position];
    }

    return CameraSettings;

  })(BaseSettings);

}).call(this);

//# sourceMappingURL=camera.js.map
