// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.SphereSettings = (function(superClass) {
    extend(SphereSettings, superClass);

    function SphereSettings(object) {
      this.object = object;
      SphereSettings.__super__.constructor.call(this, this.object);
      this.panel = $('#settings_panel');
      this.recursive = new EditBoxSettings(this.object, this.panel, 'recursive', 1);
      this.settings.push(this.recursive);
    }

    return SphereSettings;

  })(BaseObjectSettings);

}).call(this);

//# sourceMappingURL=sphere.js.map
