// Generated by CoffeeScript 1.10.0
(function() {
  "Function for front, using for menu";
  window.add_object = function(Object) {
    var object;
    object = new Object();
    return scene.add_object(object);
  };

  window.show_camera_settings = function() {
    return $('#wrapper').toggleClass('toggled');
  };

}).call(this);

//# sourceMappingURL=main.js.map
