// Generated by CoffeeScript 1.10.0
(function() {
  window.create_list = function() {
    var i, len, object, ref, select;
    select = $("#object_list");
    select.empty();
    ref = window.scene.objects;
    for (i = 0, len = ref.length; i < len; i++) {
      object = ref[i];
      select.append($("<option>").attr('value', object.name).text(object.name));
    }
    return select.on('change', function() {
      var j, len1, ref1, results;
      ref1 = window.scene.objects;
      results = [];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        object = ref1[j];
        if (object.name === this.value) {
          results.push(object.settings.load_settings());
        } else {
          results.push(void 0);
        }
      }
      return results;
    });
  };

}).call(this);

//# sourceMappingURL=object_list.js.map
