// Generated by CoffeeScript 1.10.0
(function() {
  window.save_file = function() {
    var a, blob, i, j, k, len, len1, len2, object, output, ref, ref1, ref2, setting, url;
    output = {};
    ref = window.scene.objects;
    for (i = 0, len = ref.length; i < len; i++) {
      object = ref[i];
      output[object.name] = {};
      ref1 = object.settings.settings;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        setting = ref1[j];
        output[object.name][setting.name] = setting.values;
      }
    }
    output['camera'] = {};
    ref2 = window.scene.camera.settings.settings;
    for (k = 0, len2 = ref2.length; k < len2; k++) {
      setting = ref2[k];
      output['camera'][setting.name] = setting.values;
    }
    output = JSON.stringify(output);
    blob = new Blob([output], {
      type: "application/json"
    });
    url = URL.createObjectURL(blob);
    a = document.getElementById("save_button");
    a.download = "saved_scene.json";
    return a.href = url;
  };

  window.load_file = function() {
    document.getElementById('upload').addEventListener('change', handleFileSelect, false);
    return $("#upload:hidden").trigger('click');
  };

  window.handleFileSelect = function(evt) {
    var reader;
    reader = new FileReader();
    reader.onload = onReaderLoad;
    return reader.readAsText(event.target.files[0]);
  };

  window.onReaderLoad = function(event) {
    return alert(JSON.parse(event.target.result));
  };

}).call(this);

//# sourceMappingURL=save_file.js.map
