// Generated by CoffeeScript 1.10.0
(function() {
  var objects;

  objects = [];

  window.BaseObject = (function() {
    function BaseObject() {
      this.triangles = [];
      this.settings = new BaseSettings();
    }

    return BaseObject;

  })();

}).call(this);

//# sourceMappingURL=base.js.map
