// Generated by CoffeeScript 1.10.0
(function() {
  window.Scene = (function() {
    function Scene(canvas) {
      this.canvas = canvas;
      this.objects = [];
      this.camera = new PerspectiveCamera();
      this.drawer = new Drawer(this.canvas, this.camera);
    }

    Scene.prototype.add_object = function(obj) {
      this.objects.push(obj);
      this.camera.settings.load_settings();
      window.create_list();
      return this.draw_scene();
    };

    Scene.prototype.draw_scene = function() {
      this.camera.update_matrix();
      return this.drawer.draw_objects(this.objects);
    };

    return Scene;

  })();

}).call(this);

//# sourceMappingURL=scene.js.map
